Merge all 'state/' dirs into the main 'state/' dir

diff --git a/bin/gbe b/bin/gbe
--- a/bin/gbe
+++ b/bin/gbe
@@ -54,6 +54,14 @@ function assert_utilities() {
         fi
     done
 }
+function state_dir() {
+    local gbe_subsys=${1:-$GBE_SUBSYS}
+    if [ -z "$gbe_subsys" ]; then
+        echo "ERROR: missing 'GBE_SUBSYS' variable" >&2
+        return 1
+    fi
+    echo "$BASE_DIR/state/$gbe_subsys"
+}
 
 function env_usage() {
     local b=$BOLD
@@ -84,7 +92,7 @@ function env_exports() {
 
     echo "export PATH=$PATH"
 
-    local env_creds=$BASE_DIR/state/base-env/depl-creds.yml
+    local env_creds=$(state_dir base-env)/depl-creds.yml
     if [[ ! -f "$env_creds" ]]; then
         return
     fi
@@ -98,7 +106,7 @@ function env_exports() {
     echo "export BOSH_CA_CERT=\"$(get_var /default_ca/ca)\""
     echo "export BOSH_CLIENT=admin"
     echo "export BOSH_CLIENT_SECRET=$(get_var /admin_password)"
-    echo "export BOSH_GW_PRIVATE_KEY=\"$BASE_DIR/state/base-env/jumpbox.key\""
+    echo "export BOSH_GW_PRIVATE_KEY=\"$(state_dir base-env)/jumpbox.key\""
     echo "export BOSH_ENVIRONMENT=gcp"
 }
 
@@ -433,7 +441,7 @@ function source_env() { # shim
 }
 
 function bbl_invoke() {
-    bbl --state-dir "$BASE_DIR/state/base-env" "$@"
+    bbl --state-dir "$(state_dir base-env)" "$@"
 }
 
 function setup_firewall() {
@@ -642,9 +650,9 @@ function restrict_permissions() {
 }
 
 function jumpbox_key() {
-    restrict_permissions "$BASE_DIR/state/base-env/jumpbox.key"
-    bosh int "$BASE_DIR/state/base-env/depl-creds.yml" --path /jumpbox_ssh/private_key \
-         > "$BASE_DIR/state/base-env/jumpbox.key"
+    restrict_permissions "$(state_dir base-env)/jumpbox.key"
+    bosh int "$(state_dir base-env)/depl-creds.yml" --path /jumpbox_ssh/private_key \
+         > "$(state_dir base-env)/jumpbox.key"
 }
 
 TUNNEL_PORT=5000
@@ -652,7 +660,7 @@ TUNNEL_PORT=5000
 function setup_tunnel() {
     local local_port=$1
 
-    local pid_file=$BASE_DIR/state/base-env/ssh-tunnel.pid
+    local pid_file=$(state_dir base-env)/ssh-tunnel.pid
     if has_tunnel "$pid_file"; then
         echo -e "\n${BLUE}SSH tunnel is ${BOLD}already running$RESET on PID '$(cat "$pid_file")'" \
              "(more info with ${UNDERLINE}lsof -i :$local_port$RESET)\n"
@@ -664,8 +672,8 @@ function setup_tunnel() {
     jumpbox_key
 
     nohup ssh -4 -D "localhost:$local_port" -fNC \
-            -i "$BASE_DIR/state/base-env/jumpbox.key" "jumpbox@$(jumpbox_ip)" \
-        > "$BASE_DIR/state/base-env/ssh-tunnel.log"
+            -i "$(state_dir base-env)/jumpbox.key" "jumpbox@$(jumpbox_ip)" \
+        > "$(state_dir base-env)/ssh-tunnel.log"
     lsof -i ":$local_port" \
         | grep -E '^ssh\b' | awk '{print $2}' \
         > "$pid_file"
@@ -688,7 +696,7 @@ function gbe_up() {
 }
 
 function ssh_jumpbox() {
-    if [ ! -f "$BASE_DIR/state/base-env/depl-creds.yml" ]; then
+    if [ ! -f "$(state_dir base-env)/depl-creds.yml" ]; then
         echo "$SCRIPT_NAME: ERROR: the base BOSH environment is not created yet" \
              "Please create it first. Aborting." >&2
         exit 1
@@ -713,7 +721,7 @@ function ssh_jumpbox() {
     done
 
     TERM=xterm-color ssh \
-        -i "$BASE_DIR/state/base-env/jumpbox.key" \
+        -i "$(state_dir base-env)/jumpbox.key" \
         "jumpbox@$(jumpbox_ip)" \
         "$@"
 }
@@ -746,7 +754,7 @@ case $1 in
     firewall)   setup_firewall ;;
     tunnel)
         shift
-        pid_file=$BASE_DIR/state/base-env/ssh-tunnel.pid
+        pid_file=$(state_dir base-env)/ssh-tunnel.pid
         case $1 in
             stop)
                 if has_tunnel "$pid_file"; then
@@ -767,7 +775,7 @@ case $1 in
                 ;;
             logs)
                 echo -e "${BOLD}Last logs:$RESET"
-                tail "$BASE_DIR/state/base-env/ssh-tunnel.log"
+                tail "$(state_dir base-env)/ssh-tunnel.log"
                 ;;
             *)
                 setup_tunnel "$TUNNEL_PORT"
