Update Concourse sanity tests to support being run from a GBE downstream (gbeds) project

diff --git a/deployments/concourse/fly-login b/deployments/concourse/fly-login
--- a/deployments/concourse/fly-login
+++ b/deployments/concourse/fly-login
@@ -11,34 +11,51 @@ function main() {
 
     local concourse_target=${1:-"ef"}
 
-    if [[ ! -e $BASE_DIR/bin/fly ]]; then
-        bash ${DEBUG:+"-x"} "$SUBSYS_DIR/fetch-fly-cli"
+    if [[ ! -e ${BASE_DIR}/bin/fly ]]; then
+        bash ${DEBUG:+"-x"} "${SUBSYS_DIR}/fetch-fly-cli"
     fi
-    "$BASE_DIR/bin/fly" -t "$concourse_target" sync
+    "${BASE_DIR}/bin/fly" -t "${concourse_target}" sync
 
-    "$BASE_DIR/bin/fly" -t "$concourse_target" login -k \
-        -c "https://${external_host}" -u "$atc_username" -p "$atc_password"
+    "${BASE_DIR}/bin/fly" -t "${concourse_target}" login -k \
+        -c "https://${external_host}" -u "${atc_username}" -p "${atc_password}"
     login_status=$?
 
-    if [[ $login_status -eq 0 ]]; then echo OK; else echo ERROR; fi
-    exit $login_status
+    if [[ ${login_status} -eq 0 ]]; then echo "OK"; else echo "ERROR"; fi
+    exit "${login_status}"
 }
 
 function setup() {
     SUBSYS_DIR=${SUBSYS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
     BASE_DIR=${BASE_DIR:-$(git rev-parse --show-toplevel)}
-    SUBSYS_NAME=$(spec_var /subsys/name)
+    SUBSYS_NAME=$(own_spec_var /subsys/name)
     readonly SUBSYS_DIR BASE_DIR SUBSYS_NAME
 }
 
-function creds_var() {
-    state_var depl-creds "$1"
+function own_spec_var() {
+    local path=$1
+    bosh int "${SUBSYS_DIR}/conf/spec.yml" --path "${path}"
+}
+
+function spec_var() {
+    local path=$1
+
+    local has_upstream spec_file
+    has_upstream=$(own_spec_var "/subsys/upstream" 2> /dev/null || true)
+    if [[ -n ${has_upstream} ]]; then
+        state_var "merged-spec" "${path}"
+    else
+        own_spec_var "${path}"
+    fi
 }
 
 function state_var() {
     local state_file=$1
     local path=$2
     bosh int "${BASE_DIR}/state/${SUBSYS_NAME}/${state_file}.yml" --path "${path}"
+}
+
+function creds_var() {
+    state_var "depl-creds" "$1"
 }
 
 main "$@"
